# Generated by Django 3.1.4 on 2021-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservices', '0002_auto_20210103_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
