# Generated by Django 3.1.4 on 2021-01-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
